name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/ci-cd-hello-app
          tags: |
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
    # ADICIONE ESTE PASSO AQUI
      - name: Add GitHub to known hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Checkout manifests repository
        uses: actions/checkout@v3
        with:
          repository: leoo-tech/ci-cd-hello-manifests
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: main
      
      # ADICIONE ESTE PASSO AQUI
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      
      - name: Update image tag in deployment.yaml
        run: |
          IMAGE_TAG=${{ needs.build-and-push-image.outputs.image_tag }}
          yq e '.spec.template.spec.containers[0].image = "${{ secrets.DOCKER_USERNAME }}/ci-cd-hello-app:'"$IMAGE_TAG"'"' -i deployment.yaml
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          git add deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push